DROP TABLE IF EXISTS `SensorImmediatelyValue`;
CREATE TABLE `SensorImmediatelyValue` (
    `Ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `Light` FLOAT NOT NULL DEFAULT 0.0,
    `Temperature` FLOAT NOT NULL DEFAULT 0.0,
    `HumanBody` INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (`Ts`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
INSERT INTO SensorImmediatelyValue VALUES(NULL, 0, 0, 0);
